os: linux

language: python
python: "3.9"

install:
  - pip3 install --upgrade pip 
  - pip install -q Django==$DJANGO_VERSION

env:
  - DJANGO_VERSION=3.2.2

before_script:
  - python manage.py runserver &

script:
  - python manage.py makemigrations LegacySite
  - python manage.py makemigrations
  - python manage.py migrate
  - sh import_dbs.sh
#  - python manage.py 1XSStest GiftcardSite
#  - python manage.py 2CSRFtest GiftcardSite
#  - python manage.py 3SQLtest GiftcardSite
#  - python manage.py 4HTTPtest GiftcardSite

after_script:
  - travis_terminate 0