os: linux

language: python

env:
  - DJANGO_VERSION=3.1.3

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r django-fernet-fields==0.6
  - pip install -r python-decouple
  - pip install -r django-sslserver

#script: